//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UYGS203.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public string BannerId { get; set; }
        public string BannerEstateId { get; set; }
        public string BannerUserId { get; set; }
    
        public virtual Estate Estate { get; set; }
        public virtual User User { get; set; }
    }
}
